#!/usr/bin/env bash
set -Eeuo pipefail

install -d /usr/bin/steamos-polkit-helpers
ln -sfn /usr/local/libexec/dotfiles/steamos-update \
	/usr/bin/steamos-update
ln -sfn /usr/local/libexec/dotfiles/steamos-restart-display-manager \
	/usr/bin/steamos-polkit-helpers/steamos-restart-sddm
