#!/usr/bin/env bash
set -Eeuo pipefail

rules_dir=/usr/local/libexec/system-ufw-rules.d
[[ -d $rules_dir ]] || exit 0

while IFS= read -r -d '' rules; do
	"$rules"
done < <(find "$rules_dir" -maxdepth 1 -type f -executable -print0 | sort -z)
