#!/usr/bin/env bash
## Firefox
## https://www.firefox.com
set -Eeuo pipefail

source "$SETUP_ROOT/lib/module.sh"
source "$SETUP_ROOT/lib/json.sh"
source "$SETUP_ROOT/lib/browsers.sh"

packages=(
	firefox jq
	arch:aur/arkenfox-user.js
	fedora:rpmspec/arkenfox-user.js
)

arkenfox_require_template() {
	local template=${ARKENFOX_TEMPLATE:-/usr/share/arkenfox-user.js/user.js}
	[[ -r $template && -s $template ]] || {
		printf 'Arkenfox template missing or empty: %s. Install arkenfox-user.js before browsers/firefox apply; inspect /var/log/system/package-plan.tsv and packages.log.\n' "$template" >&2
		return 1
	}
}

firefox_install_directory() {
	if [[ -n ${FIREFOX_INSTALL_DIR:-} ]]; then
		printf '%s\n' "$FIREFOX_INSTALL_DIR"
	elif [[ -x /usr/lib64/firefox/firefox ]]; then
		printf '%s\n' /usr/lib64/firefox
	else
		printf '%s\n' /usr/lib/firefox
	fi
}

firefox_policies() {
	jq --arg distro "$DISTRO" '
		{policies: {
			Extensions: {Install: [.extensions[] | .firefox // empty]},
			SearchEngines: {Add: [
				((.search_engines.distro_engines[$distro] // []) + .search_engines.common_engines)[]
				| {Name: .name, URLTemplate: .template, IconURL: .icon, Alias: .alias}
			]}
		}}
	' <<<"${1:?browser configuration required}" | firefox_merge_feature_policies
}

module_apply() {
	arkenfox_require_template
	BROWSERS_CONFIG=$(json_strip_comments "$MODULE_DIR/common.jsonc")

	# AutoConfig applies Arkenfox to the profile Firefox actually selects.
	# pref() has the same startup-reset behavior as user.js, without locking prefs.
	# shellcheck disable=SC2034 # read via nameref in gecko_generate_userjs
	declare -A USER_PREFS=(
		# Enable restoring previous session
		["browser.startup.page"]=3
		["browser.sessionstore.enabled"]=true
		["browser.sessionstore.privacy_level"]=0

		# Use native XDG file picker
		["widget.use-xdg-desktop-portal.file-picker"]=1

		# Allow any search engine in about:preferences#search (https://superuser.com/a/1756774/204761)
		["browser.urlbar.update2.engineAliasRefresh"]=true

		["dom.webgpu.enabled"]=true
		["signon.rememberSignons"]=false # Already using BitWarden for that

		# Right-click on sites that disable it: hold Shift while right-clicking.
		# To always open Firefox's context menu (no Shift needed):
		# ["dom.event.contextmenu.enabled]=false
		# With the default true, this controls whether Shift+right-click suppresses
		# the page handler:
		["dom.event.contextmenu.shift_suppresses_event"]=true
	)

	local firefox_dir
	firefox_dir=$(firefox_install_directory)
	[[ -x $firefox_dir/firefox ]] || {
		printf 'Firefox installation missing: %s\n' "$firefox_dir" >&2
		return 1
	}
	{
		# Firefox skips the first line of an AutoConfig file.
		printf '// Arkenfox plus local preferences, generated by browsers/firefox.\n'
		printf 'var user_pref = pref;\n'
		cat "${ARKENFOX_TEMPLATE:-/usr/share/arkenfox-user.js/user.js}"
		printf '\n'
		gecko_generate_userjs USER_PREFS
	} | file_write "$firefox_dir/arkenfox.cfg"
	printf '%s\n' \
		'pref("general.config.filename", "arkenfox.cfg");' \
		'pref("general.config.obscure_value", 0);' |
		file_write "$firefox_dir/defaults/pref/arkenfox.js"

	# Firefox owns extension installation/updates and its search database.
	firefox_policies "$BROWSERS_CONFIG" |
		file_write "$firefox_dir/distribution/policies.json"
}

module_healthcheck() {
	arkenfox_require_template
	local firefox_dir
	firefox_dir=$(firefox_install_directory)
	[[ -s $firefox_dir/arkenfox.cfg &&
		-s $firefox_dir/defaults/pref/arkenfox.js ]] || {
		printf 'Firefox AutoConfig was not generated.\n' >&2
		return 1
	}
	jq -e '.policies.Extensions.Install | length > 0' "$firefox_dir/distribution/policies.json" >/dev/null
}

module_entrypoint "$@"
