# UI
autofit=70%
osc=no
script-opts-append=uosc-disable_elements=idle_indicator

# Video
vo=gpu-next
hwdec=auto

# Audio
ao=pipewire
alang=jpn,jp,eng,en
volume-max=300

# Subtitles
slang=eng,en,bg,vi,vn
sub-auto=fuzzy
# sub-codepage=cp1251

# Screenshots
screenshot-directory=~/Pictures
screenshot-template=mpv-%f-%wH.%wM.%wS.%wT-#%#00n

# The module selects generic-high after generating the shader profiles.
