#!/usr/bin/env bash

install_base_system() {
	distro_install_base_system
}

write_fstab() {
	local slot=$1
	local btrfs_uuid esp_uuid
	btrfs_uuid=$(blkid -s UUID -o value "$MAPPER_DEVICE")
	esp_uuid=$(blkid -s UUID -o value "$ESP_PARTITION")

	cat >"$TARGET_ROOT/etc/fstab" <<EOF
# Generated by $PROJECT_ID.
UUID=$btrfs_uuid / btrfs $BTRFS_MOUNT_OPTIONS,subvol=$slot 0 0
UUID=$btrfs_uuid /home btrfs $BTRFS_MOUNT_OPTIONS,subvol=$HOME_SUBVOLUME 0 0
UUID=$esp_uuid /efi vfat umask=0077 0 2
EOF
}

configure_base_system() {
	local slot=$1
	log "Configuring $DISTRO base system"

	write_fstab "$slot"
	printf '%s\n' "$HOSTNAME" >"$TARGET_ROOT/etc/hostname"
	cat >"$TARGET_ROOT/etc/hosts" <<EOF
127.0.0.1 localhost
::1 localhost
127.0.1.1 $HOSTNAME.localdomain $HOSTNAME
EOF

	printf 'KEYMAP=%s\n' "$KEYMAP" >"$TARGET_ROOT/etc/vconsole.conf"
	printf 'LANG=%s\n' "$LOCALE" >"$TARGET_ROOT/etc/locale.conf"
	distro_configure_base_system
	target_chroot ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
	target_chroot hwclock --systohc

	if ! target_chroot getent group "$USER_GID" >/dev/null 2>&1; then
		target_chroot groupadd --gid "$USER_GID" "$USERNAME"
	fi
	if ! target_chroot id "$USERNAME" >/dev/null 2>&1; then
		target_chroot useradd \
			--uid "$USER_UID" \
			--gid "$USER_GID" \
			--no-create-home \
			--shell "$USER_SHELL" \
			"$USERNAME"
	fi

	mkdir -p "$TARGET_ROOT/etc/skel" "$TARGET_ROOT/etc/$PROJECT_ID"
}

set_initial_password() {
	log "Set the login password for $USERNAME"
	target_chroot passwd "$USERNAME"
}

copy_login_password() {
	local password_hash
	password_hash=$(awk -F: -v user="$USERNAME" '$1 == user { print $2; exit }' /etc/shadow)
	[[ -n $password_hash ]] || die "Could not read password hash for $USERNAME"
	target_chroot usermod --password "$password_hash" "$USERNAME"
}

finalize_target_security() {
	if declare -F distro_finalize_security >/dev/null; then
		distro_finalize_security
	fi
}
